# Generated by Django 2.0.3 on 2018-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='First Name')),
                ('password', models.IntegerField(max_length=10, verbose_name='password')),
            ],
        ),
    ]
